create table bolum(
	ID varchar(255) not null,
	BOLUM_ADI varchar(255),
	BOLUM_KODU varchar(10),
	PRIMARY KEY(ID)
)

create table sekreter(
    ID VARCHAR(255) NOT NULL,
    AD_SOYAD VARCHAR(255),
    SIFRE VARCHAR(255),
    BOLUM_ID VARCHAR(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (BOLUM_ID) REFERENCES bolum(ID)
)

create table ders(
	ID VARCHAR(255) NOT NULL,
	AD VARCHAR(255),
	KOD VARCHAR(255),
	KREDI VARCHAR(255),
	PRIMARY KEY(ID)    
)

create table ogrenci(
	ID VARCHAR(255) NOT NULL,
	AD_SOYAD VARCHAR(255),
	NUMARA VARCHAR(255),
	SINF VARCHAR(255),
	BURS_DURUM VARCHAR(255),
    PRIMARY KEY(ID)
)

create table donem(
	ID VARCHAR(255) NOT NULL,
    AD VARCHAR(255),
    PRIMARY KEY(ID)
)

CREATE TABLE SEKRETER_BOLUM(
	ID VARCHAR(255) NOT NULL,
	SEKRETER_ID VARCHAR(255),
    BOLUM_ID VARCHAR(255),
    PRIMARY KEY(ID),
    FOREIGN KEY(SEKRETER_ID) REFERENCES SEKRETER(ID),
    FOREIGN KEY(BOLUM_ID) REFERENCES BOLUM(ID)
)

CREATE TABLE BOLUM_DERS(
	ID VARCHAR(255) NOT NULL,
	BOLUM_ID VARCHAR(255),
	DERS_ID VARCHAR(255),
	PRIMARY KEY(ID),
	FOREIGN KEY(BOLUM_ID) REFERENCES BOLUM(ID),
	FOREIGN KEY(DERS_ID) REFERENCES DERS(ID)    
)

CREATE TABLE OGRENCI_DERS(
	ID VARCHAR(255) NOT NULL,
	OGRENCI_ID VARCHAR(255),
	DERS_ID VARCHAR(255),
	DONEM_ID VARCHAR(255),
	OGRENCI_NOT VARCHAR(10),
	PRIMARY KEY(ID),
    FOREIGN KEY(OGRENCI_ID) REFERENCES OGRENCI(ID),
    FOREIGN KEY(DERS_ID) REFERENCES DERS(ID),
    FOREIGN KEY(DONEM_ID) REFERENCES DONEM(ID)
)